{
	"version": 1542149012,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/water-sheet0.png",
		"images/crimson-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/spawn1-sheet0.png",
		"images/island-sheet0.png",
		"images/island2-sheet0.png",
		"images/island3-sheet0.png",
		"images/blue-sheet0.png",
		"images/icy-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/newpiskel-sheet0.png",
		"images/newpiskel2-sheet0.png",
		"images/intro-sheet0.png",
		"images/intro2-sheet0.png",
		"images/newpiskel3-sheet0.png",
		"images/intro3-sheet0.png",
		"images/intro4-sheet0.png",
		"images/newpiskel4-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/inttro-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/intro5-sheet0.png",
		"images/intro6-sheet0.png",
		"images/newpiskel5-sheet0.png",
		"images/newpiskel6-sheet0.png",
		"images/tiledbackground.png",
		"images/start1-sheet0.png",
		"images/player-sheet0.png",
		"images/newpiskel7-sheet0.png",
		"images/spawn4-sheet0.png",
		"images/crimsonisland1-sheet0.png",
		"images/crimsonisland2-sheet0.png",
		"images/crimsonisland3-sheet0.png",
		"images/crimsonisland4-sheet0.png",
		"images/merchant-sheet0.png",
		"images/encountersheet-sheet0.png",
		"images/shipwrecked-sheet0.png",
		"images/enemy-sheet0.png",
		"images/enemyspawn-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/crimsonenemy-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/clue1-sheet0.png",
		"images/key-sheet0.png",
		"images/cluebg-sheet0.png",
		"images/newpiskel8-sheet0.png",
		"images/newpiskel10-sheet0.png",
		"images/keyicon-sheet0.png",
		"images/coins-sheet0.png",
		"images/kraken-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/tentacleball-sheet0.png",
		"images/tentacleball3-sheet0.png",
		"images/tentacleball2-sheet0.png",
		"images/newpiskel13-sheet0.png",
		"images/gameoverskull-sheet0.png",
		"images/keyspawn-sheet0.png",
		"media/piraat- volledig.m4a",
		"media/piraat- volledig.ogg",
		"media/jelly legs bruno bg music.m4a",
		"media/jelly legs bruno bg music.ogg",
		"media/crimson bg music.ogg",
		"media/cannon sound.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"animated menu.webm",
		"pathfind.js"
	]
}